//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollageDevices
{
    using System;
    using System.Collections.Generic;
    
    public partial class Devices
    {
        public int id { get; set; }
        public string name { get; set; }
        public string inventnumber { get; set; }
        public string category { get; set; }
        public string description { get; set; }
        public string cabinet { get; set; }
        public string comment { get; set; }
    }
}
